#!/bin/bash
# Quick Start Guide for Astra Chatbot

echo "🚀 Astra Chatbot - Quick Start"
echo "================================"
echo ""
echo "📁 Project Location: /home/astra/astra_chatbot"
echo ""
echo "✅ Prerequisites Check:"
echo "  - Ollama: $(systemctl is-active ollama 2>/dev/null || echo 'NOT RUNNING')"
echo "  - Python venv: $([ -d .venv ] && echo 'EXISTS' || echo 'MISSING')"
echo "  - PDF: $([ -f ubuntu-linux-toolbox*.pdf ] && echo 'FOUND' || echo 'MISSING')"
echo ""
echo "🎯 To Start:"
echo "  ./run.sh"
echo ""
echo "OR:"
echo "  source .venv/bin/activate"
echo "  python astra_chatbot.py"
echo ""
echo "💡 Example Commands to Try:"
echo "  - Install VS Code"
echo "  - Update all packages"
echo "  - Setup Docker"
echo "  - Check disk space"
echo ""
echo "💬 Example Questions:"
echo "  - How do I check disk space?"
echo "  - What's the difference between apt and snap?"
echo "  - Explain Linux file permissions"
echo ""
echo "📚 Documentation:"
echo "  - README.md - Full documentation"
echo "  - PROJECT_SUMMARY.md - Technical details"
echo "  - CLEANUP_SUMMARY.md - What changed"
echo ""
echo "🎨 UI Features:"
echo "  - Sidebar: Chat history + Settings"
echo "  - Main: Chat area + Input"
echo "  - Themes: Dark (default) / Light"
echo "  - Export: Save to Markdown"
echo ""
echo "🔧 Troubleshooting:"
echo "  - If Ollama not running: sudo systemctl start ollama"
echo "  - If Qt errors: sudo apt install libxcb-cursor0 libxcb-xinerama0"
echo "  - If PDF slow: First run extracts text (30-60s), then cached"
echo ""
